### ISSUE TITLE
Il sito web è off musi marsi

### ISSUE THREAD

**Issue by SonoKevin** [Debianissimo/website#1]
## Description
> Briefly describe your issue here.

---
## Steps to reproduce
1. …
1. …
1. …

### Screenshots

> You can take a screenshot of the problem and paste it here, if possible.

---
## Expected behavior
> A clear and concise description of what you expected to happen.

---
## Platform info
| | |
|-|-|
| **OS/Platform** |  |
| **Browser version** |  |
| **Device type** |  |
| **Viewport size** (screen resolution, browser width… etc) |  |
| **Device** |  |

---
### Additional context

> Do you have anything else to add? Put it here!

**Comment by th3at0m** [comment]
Il problema non verra' sistemato.

**Comment by PsykeDady** [comment]
Il sito web era statico? Posso suggerire di utilizzare una github pages oppure surge.sh per ricaricarlo? 

Secondo me è un pezzo di storia va preservato
