### ISSUE TITLE
Il sito e off

### ISSUE THREAD

**Issue by Leonardo5681** [Debianissimo/website#2]
Buongiorno,oggi volevo provare Debianissimo,però il sito non va.Potreste risolvere?

**Comment by padrepio666** [comment]
Glielo paghi tu il dominio????

**Comment by IlNonoP09** [comment]
ci sarà un modo per avere un sito non dovendolo pagare.... credo....

**Comment by padrepio666** [comment]
Quando non si sanno le cose, sarebbe più carino non parlare a sproposito e non fare figure di merda.
